# Generated by Django 5.2.5 on 2025-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SawMill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('pieces_per_cube', models.CharField(max_length=50)),
                ('price_1s_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_1s_cube', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_2s_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_2s_cube', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Пиломатериал',
                'db_table': 'sawmill.products',
            },
        ),
    ]
